# Generated by Django 5.0.12 on 2025-03-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "custId",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("firstname", models.CharField(max_length=20)),
                ("lastname", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "signupInfo",
            },
        ),
    ]
